### ISSUE TITLE
Working with FLAVOR

### ISSUE THREAD

**Issue by Ishayahu** [freebsd/portmaster#55]
===>>> The accessibility/py3-atspi port moved to accessibility/py-atspi@py36
===>>> Reason: Moved to a flavored, generic, version

Now it doesn't works with ports moved to a flavored version

**Comment by serge-vk** [comment]
This is still the case with the latest portmaster 3.19_8. For any port with py27 and py36 flavours installed I get something like this:
       Package version: py36-cffi-1.11.5
       Latest version:  py27-cffi-1.11.5
	===>>> py36-cffi-1.11.5.txz matches the installed version
	===>>> Path: /var/ports/packages/All/py36-cffi-1.11.5.txz

	===>>> Delete stale package: py36-cffi-1.11.5.txz? y/n [n]

**Comment by Ishayahu** [comment]
Last two month all upgrades with portmaster were without errors, I thougt it was done allready...

**Comment by stesser** [comment]
The port has been updated to version 3.26, which should fix this issue for ports with flavors.
The fix does only apply to flavored ports (some have the issue due to an interpreter version prefix in the package name despite not using flavors) and it does not support the combination of --clean-packages with --index or --index-only, since the index does not contain any information about package flavors.
